# Generated by Django 3.1.5 on 2021-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviescreens',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='moviescreentime',
            name='available_seats',
            field=models.IntegerField(default=50),
        ),
    ]
